import React,{useState}from'react';
export interface InfoRecord {id:string;name:string;phone?:string;email?:string;car?:string;plate?:string;unit?:string;photo?:string}
const fields=[['name','name'],['phone','phone number'],['email','email address'],['car','car information'],['plate','license plate'],['unit','unit number'],['photo','photo']]as const;
export function RequestMissingInfo({person}:{person:InfoRecord}):React.JSX.Element{
 const [open,setOpen]=useState(false);const [selected,setSelected]=useState<string[]>([]);const [mode,setMode]=useState('missing');const [channel,setChannel]=useState('');const [body,setBody]=useState('');
 const start=()=>{setSelected(fields.filter(([key])=>!person[key]?.trim()).map(([key])=>key));setChannel(person.email?'email':person.phone?'message':'');setMode('missing');setBody('');setOpen(true);};
 const generate=()=>{const labels=fields.filter(([key])=>selected.includes(key)).map(([,label])=>label);const list=labels.length===1?labels[0]:labels.slice(0,-1).join(', ')+' and '+labels.at(-1);setBody(!labels.length?'':mode==='review'?`Hi, please review your ${list} for the Refuah V'Chesed volunteer roster and send any corrections. Thank you.`:`Hi, it looks like we're missing your ${list} for the Refuah V'Chesed volunteer roster. Please send the missing information. Thank you.`);};
 return <><button onClick={start}>Request missing info</button>{open&&<section role="dialog" aria-modal="false" aria-label={`Request information for ${person.name}`} className="space-y-3"><h3>Request information: {person.name}</h3><p>Draft only. Contact details are from source records, not verified delivery routes. Nothing is sent or saved.</p><label>Request type<select value={mode} onChange={e=>setMode(e.target.value)}><option value="missing">Missing information</option><option value="review">Review existing information</option></select></label><fieldset><legend>Choose fields</legend>{fields.map(([key,label])=><label key={key} style={{display:'flex',alignItems:'center',gap:8}}><input style={{width:'auto'}} type="checkbox" checked={selected.includes(key)} onChange={e=>setSelected(s=>e.target.checked?[...s,key]:s.filter(k=>k!==key))}/>{label}</label>)}</fieldset><label>Proposed channel<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="">No channel selected</option>{person.email&&<option value="email">Email</option>}{person.phone&&<option value="message">Message (service unverified)</option>}</select></label><label>Proposed recipient<input readOnly value={(channel==='email'?person.email:channel==='message'?person.phone:'')??''}/></label><p>Verify this recipient belongs to this person before sending. A phone number does not establish SMS, WhatsApp or an existing thread.</p><button disabled={!selected.length} onClick={generate}>Generate editable preview</button><label>Message preview<textarea rows={6} value={body} onChange={e=>setBody(e.target.value)}/></label><button disabled title="Delivery is not enabled. Recipient, wording and sending setup need separate review.">Send (not enabled)</button><button onClick={()=>setOpen(false)}>Close draft</button><p>Closing or leaving discards this draft. No email drafts, message links, updates or automated notifications are created.</p></section>}</>;
}
