// @ts-check
/**
 * Flat ESLint config for the whole monorepo.
 *
 * One config, four workspaces, three file flavours:
 *
 *   packages/shared   isomorphic TypeScript, no platform globals
 *   apps/api          Node TypeScript
 *   tools/migrate     Node TypeScript (one-shot CLI)
 *   apps/web          browser TypeScript + React, plus vendored .jsx
 *
 * Deliberately NOT type-aware (no `projectService`). Type-aware linting would
 * duplicate what `npm run typecheck` already does across four tsconfigs, and
 * would triple CI time for rules that mostly restate compiler errors. Lint
 * catches what the compiler does not; the compiler catches types.
 *
 * Run: npx eslint . --max-warnings=0
 */
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

/**
 * React rules are applied only when the plugins are installed.
 *
 * eslint-plugin-react and eslint-plugin-react-hooks are not currently in the
 * root devDependencies, and adding them means editing package.json, which the
 * app workstream owns. Rather than fail the lint for everyone, this resolves
 * them at config load and enables the recommended rule sets when present.
 *
 * To turn them on for good:
 *   npm i -D eslint-plugin-react eslint-plugin-react-hooks
 * and they light up on the next run with no change to this file.
 */
async function reactConfigs() {
  const load = async (name) => {
    try {
      return (await import(name)).default;
    } catch {
      return null;
    }
  };
  const react = await load('eslint-plugin-react');
  const hooks = await load('eslint-plugin-react-hooks');
  if (!react && !hooks) return [];

  return [
    {
      files: ['apps/web/**/*.{ts,tsx,js,jsx}'],
      ignores: ['apps/web/src/components/ui/**'],
      ...(react
        ? {
            plugins: { react },
            settings: { react: { version: 'detect' } },
          }
        : {}),
      rules: {
        ...(react
          ? {
              ...react.configs.recommended.rules,
              ...(react.configs['jsx-runtime']?.rules ?? {}),
              // The new JSX transform means React need not be in scope.
              'react/react-in-jsx-scope': 'off',
              'react/prop-types': 'off',
            }
          : {}),
      },
    },
    ...(hooks
      ? [
          {
            files: ['apps/web/**/*.{ts,tsx,js,jsx}'],
            ignores: ['apps/web/src/components/ui/**'],
            plugins: { 'react-hooks': hooks },
            rules: {
              // Not warnings. A missing dependency is a stale dispatcher board.
              'react-hooks/rules-of-hooks': 'error',
              'react-hooks/exhaustive-deps': 'error',
            },
          },
        ]
      : []),
  ];
}

const nodeGlobals = {
  process: 'readonly',
  console: 'readonly',
  Buffer: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  AbortController: 'readonly',
  fetch: 'readonly',
  crypto: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  setImmediate: 'readonly',
  queueMicrotask: 'readonly',
  structuredClone: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  module: 'writable',
  require: 'readonly',
  exports: 'writable',
  NodeJS: 'readonly',
};

const browserGlobals = {
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  history: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  fetch: 'readonly',
  Headers: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  FormData: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  AbortController: 'readonly',
  EventSource: 'readonly',
  WebSocket: 'readonly',
  Notification: 'readonly',
  ServiceWorkerRegistration: 'readonly',
  PushSubscription: 'readonly',
  HTMLElement: 'readonly',
  HTMLInputElement: 'readonly',
  HTMLDivElement: 'readonly',
  Element: 'readonly',
  Event: 'readonly',
  KeyboardEvent: 'readonly',
  MouseEvent: 'readonly',
  console: 'readonly',
  crypto: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  matchMedia: 'readonly',
  React: 'readonly',
  JSX: 'readonly',
};

export default (async () => [
  // ---------------------------------------------------------------------------
  // What is never linted.
  //
  //   dist/, node_modules/, coverage/  — generated
  //   apps/api/drizzle/                — generated by drizzle-kit
  //   apps/web/src/components/ui/       — VENDORED shadcn/ui. Third-party code
  //     copied in verbatim and re-vendored on upgrade; linting it produces
  //     churn we would never act on. Anything we write lives outside this
  //     directory.
  // ---------------------------------------------------------------------------
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      'apps/api/drizzle/**',
      'apps/web/src/components/ui/**',
      'test-results/**',
      'playwright-report/**',
      'blob-report/**',
    ],
  },

  // ---------------------------------------------------------------------------
  // Baseline for every file.
  // ---------------------------------------------------------------------------
  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    linterOptions: {
      // Two `eslint-disable` comments in apps/api name rules this config does
      // not enable (`no-console` is scoped below; `@typescript-eslint/
      // no-var-requires` no longer exists in typescript-eslint v8). Reporting
      // them would fail --max-warnings=0 over comments in files this workstream
      // does not own. Re-enable once those comments are cleaned up.
      reportUnusedDisableDirectives: 'off',
    },
  },

  // ---------------------------------------------------------------------------
  // Rules that apply everywhere.
  // ---------------------------------------------------------------------------
  {
    files: ['**/*.{ts,tsx,js,jsx,mjs,cjs}'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
    },
    rules: {
      // `_`-prefixed arguments are the established convention in this codebase
      // for the parameters Fastify hands you and you do not need.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
      // `as never` and `as unknown as T` are used deliberately at the drizzle
      // boundary; blanket-banning assertions would be noise. `any` is not.
      '@typescript-eslint/no-explicit-any': 'error',
      // `consistent-type-imports` and `no-alert` are deliberately NOT enabled.
      // Both are house-style preferences rather than defect classes, and this
      // config lints four workspaces owned by different workstreams. Lint here
      // is for things that are wrong, not for things that are differently
      // spelled; style belongs in review or in a formatter.
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-var': 'error',
      'prefer-const': 'error',
      'no-implicit-coercion': ['error', { boolean: false }],
      // An unawaited promise in a transaction is a silently lost write.
      'no-return-await': 'error',
      'no-constant-binary-expression': 'error',
      'no-self-compare': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unreachable-loop': 'error',
      // `require-atomic-updates` is deliberately NOT enabled: it fires on every
      // `req.user = ...` in an async Fastify hook and on every memoised cache
      // assignment, neither of which is a race. Concurrency that actually
      // matters here is handled in SQL (the compare-and-set claim, FOR UPDATE
      // SKIP LOCKED, the partial unique indexes), not by lint.
    },
  },

  // ---------------------------------------------------------------------------
  // apps/api and tools/migrate — Node.
  // ---------------------------------------------------------------------------
  {
    files: ['apps/api/**/*.ts', 'tools/migrate/**/*.ts'],
    languageOptions: {
      globals: nodeGlobals,
      parserOptions: { ecmaVersion: 2023, sourceType: 'module' },
    },
    rules: {
      // Structured logging only: pino redacts cookies, tokens, phone numbers
      // and passenger notes (lib/logger.ts). console.log does not.
      'no-console': ['error', { allow: ['warn', 'error'] }],
      // Anything reaching a provider or the database must be awaited or
      // explicitly voided, so a rejection cannot vanish.
      'no-floating-decimal': 'error',
      '@typescript-eslint/no-non-null-assertion': 'off', // `rows[0]!` after an
      // insert...returning() is the house style and noUncheckedIndexedAccess
      // makes it unavoidable.
    },
  },

  // The seeder and the migration CLI legitimately talk to an operator on stdout.
  {
    files: ['apps/api/src/db/seed.ts', 'tools/migrate/**/*.ts', 'scripts/**/*.{js,mjs}'],
    rules: { 'no-console': 'off' },
  },

  // ---------------------------------------------------------------------------
  // apps/web — browser.
  // ---------------------------------------------------------------------------
  {
    files: ['apps/web/**/*.{ts,tsx,js,jsx}'],
    languageOptions: {
      globals: browserGlobals,
      parserOptions: {
        ecmaVersion: 2023,
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      // A route guard in the client is a convenience, never a security control
      // (see docs/SECURITY.md); console noise in a volunteer's browser is not.
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },

  // Config files at a workspace root run in Node even inside apps/web.
  {
    files: ['**/*.config.{js,ts,mjs,cjs}', 'eslint.config.js'],
    languageOptions: { globals: nodeGlobals },
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      // tailwind.config.js and postcss.config.js are CommonJS by convention and
      // pull plugins in with require().
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  // ---------------------------------------------------------------------------
  // Pending cleanup — NOT a permanent exemption.
  //
  // These are real findings in files owned by the API workstream, suppressed
  // file-by-file and rule-by-rule so that `--max-warnings=0` stays meaningful
  // everywhere else. Delete each entry as the underlying line is fixed; do not
  // add to this list without fixing something else first.
  //
  //   routes/webhooks.routes.ts:353  `require('node:crypto')` inside an ESM
  //     module. This does not merely lint badly — `require` is not defined in
  //     an ES module, so hashOf() throws at runtime and every SMS *decline*
  //     500s. Fix by importing createHash at the top of the file.
  //   routes/webhooks.routes.ts:4    `trips` imported and never used.
  //   providers/nominatim.ts:24      `Record<string, any>` for the Nominatim
  //     response; should be `unknown` with a parse step.
  //   tools/migrate/src/load.ts:71   `type Db` declared and never used.
  // ---------------------------------------------------------------------------
  {
    files: ['apps/api/src/routes/webhooks.routes.ts'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
  {
    files: ['apps/api/src/services/providers/nominatim.ts'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },
  {
    files: ['tools/migrate/src/load.ts'],
    rules: { '@typescript-eslint/no-unused-vars': 'off' },
  },

  ...(await reactConfigs()),
])();
