/** Isolated roster issuance. Never calls user/card/vehicle/dispatch services. */
import type {FastifyInstance}from'fastify';
import{z}from'zod';import{sql}from'../db/client.js';import{requireAdmin,currentUser}from'../auth/guards.js';import{Errors}from'../lib/errors.js';import{generateToken,hashToken,encryptField,decryptField}from'../lib/crypto.js';import{cardValidity,validityDisclosure}from'../domain/roster-card-validity.js';
const issue=z.object({rosterId:z.string().uuid(),kind:z.enum(['volunteer','vehicle']),activeConfirmed:z.literal(true),photoConfirmed:z.literal(true),plateConfirmed:z.boolean(),revision:z.number().int().positive()}).strict();
const vehicleDisclosureApproved=true;
export async function rosterCardActivationRoutes(app:FastifyInstance):Promise<void>{
 app.get('/api/admin/roster-cards',{preHandler:requireAdmin},async(_req,reply)=>{reply.header('Cache-Control','private, no-store');const cards=await sql`SELECT id,roster_id,kind,state,revision,expires_at,token_cipher FROM roster_verification_cards ORDER BY issued_at`;return{cards:cards.map(c=>({...c,token_cipher:undefined,token:decryptField(c.token_cipher)}))};});
 app.post('/api/admin/roster-cards/issue',{preHandler:requireAdmin},async(req,reply)=>{
 reply.header('Cache-Control','private, no-store');const p=issue.safeParse(req.body);if(!p.success)throw Errors.validation('Confirm the person, photo and card details before issuing');const i=p.data;
 return sql.begin(async tx=>{await tx`SELECT pg_advisory_xact_lock(713104096)`;const rows=await tx`SELECT p.*,r.full_name FROM card_preparations p JOIN volunteer_roster_drafts r ON r.id=p.roster_id WHERE p.roster_id=${i.rosterId} FOR UPDATE`;const r=rows[0];if(!r||r.revision!==i.revision)throw Errors.conflict('Save and reload the reviewed preparation first');const f=r.fields as {name:string;number:string;unit:string;photo:string|null;plate:string;expiry:string;make?:string;model?:string;year?:string};if(!f.photo||!f.name||!/^\d{1,3}$/.test(f.number)||Number(f.number)<1||f.number!==f.unit||!/^\d{4}-(0[1-9]|1[0-2])$/.test(f.expiry))throw Errors.validation('Name, number, photo and expiry are required');if(i.kind==='vehicle'&&(!i.plateConfirmed||!f.plate.trim()||!f.make?.trim()||!f.model?.trim()||!/^(19|20)\d{2}$/.test(f.year??'')))throw Errors.validation('Vehicle make, model, year and plate must be entered and confirmed');
 const [y,m]=f.expiry.split('-').map(Number);const expires=new Date(Date.UTC(y!,m!,1));if(expires.getTime()<=Date.now())throw Errors.validation('Choose a future expiry');
 const token='rr_'+generateToken();const cipher=encryptField(token);
 const old=await tx`UPDATE roster_verification_cards SET state='revoked',revision=revision+1 WHERE roster_id=${i.rosterId} AND kind=${i.kind} AND state<>'revoked' RETURNING id`;for(const o of old)await tx`INSERT INTO roster_card_status_events(card_id,actor_id,state)VALUES(${o.id},${currentUser(req).id},'revoked')`;
 const created=await tx`INSERT INTO roster_verification_cards(roster_id,kind,token_hash,token_cipher,state,active_confirmed,public_name,unit_number,public_photo,vehicle_details,expires_at)VALUES(${i.rosterId},${i.kind},${hashToken(token)},${cipher},'active',true,${f.name},${f.number},${f.photo},${i.kind==='vehicle'?tx.json({make:f.make!,model:f.model!,year:f.year!,plate:f.plate}):null},${expires.toISOString()})RETURNING id,revision`;
 await tx`INSERT INTO roster_card_status_events(card_id,actor_id,state)VALUES(${created[0]!.id},${currentUser(req).id},'active')`;return{card:{...created[0],token,kind:i.kind,state:'active'}};
 });});
 app.patch<{Params:{id:string}}>('/api/admin/roster-cards/:id/status',{preHandler:requireAdmin},async(req,reply)=>{reply.header('Cache-Control','private, no-store');const p=z.object({state:z.enum(['active','lost','revoked','inactive']),revision:z.number().int().positive(),activeConfirmed:z.boolean().optional()}).strict().safeParse(req.body);if(!p.success||!z.string().uuid().safeParse(req.params.id).success)throw Errors.validation('Invalid card status');if(p.data.state==='active'&&!p.data.activeConfirmed)throw Errors.validation('Confirm the person is still active');return sql.begin(async tx=>{const old=await tx`SELECT state,revision FROM roster_verification_cards WHERE id=${req.params.id} FOR UPDATE`;if(!old.length)throw Errors.notFound('Card');if(old[0]!.revision!==p.data.revision)throw Errors.conflict('Reload current status');if(old[0]!.state==='revoked'&&p.data.state==='active')throw Errors.conflict('Revoked tokens cannot be reactivated; reissue a new card');const result=await tx`UPDATE roster_verification_cards SET state=${p.data.state},revision=revision+1 WHERE id=${req.params.id} RETURNING revision`;await tx`INSERT INTO roster_card_status_events(card_id,actor_id,state)VALUES(${req.params.id},${currentUser(req).id},${p.data.state})`;return{revision:result[0]!.revision};});});
 app.post<{Params:{token:string}}>('/api/roster-cards/verify/:token/report',{bodyLimit:20_000,config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(req,reply)=>{reply.header('Cache-Control','no-store');const p=z.object({reporterName:z.string().trim().min(1).max(120),organizationType:z.enum(['hospital','law enforcement','other agency','private company','other']),organizationName:z.string().trim().min(1).max(160),contact:z.string().trim().min(3).max(180),reportType:z.enum(['report conduct','official complaint','comment','found card']),message:z.string().trim().min(1).max(4000)}).strict().safeParse(req.body);if(!p.success)throw Errors.validation('Complete the reporter identity, organization, contact and message');if(!/^rr_[A-Za-z0-9_-]{43}$/.test(req.params.token))throw Errors.notFound('Card');const rows=await sql`SELECT id FROM roster_verification_cards WHERE token_hash=${hashToken(req.params.token)}`;if(!rows.length)throw Errors.notFound('Card');const v=p.data;await sql`INSERT INTO roster_card_reports(card_id,reporter_name,organization_type,organization_name,contact,report_type,message)VALUES(${rows[0]!.id},${v.reporterName},${v.organizationType},${v.organizationName},${v.contact},${v.reportType},${v.message})`;return{received:true,identityStatus:'unverified'};});
 app.get('/api/admin/roster-card-reports',{preHandler:requireAdmin},async(_req,reply)=>{reply.header('Cache-Control','private, no-store');return{reports:await sql`SELECT * FROM roster_card_reports ORDER BY created_at DESC LIMIT 100`};});
 app.get<{Params:{token:string}}>('/api/roster-cards/verify/:token',{config:{rateLimit:{max:30,timeWindow:'1 minute'}}},async(req,reply)=>{reply.header('Cache-Control','no-store').header('Pragma','no-cache').header('Referrer-Policy','no-referrer');if(!/^rr_[A-Za-z0-9_-]{43}$/.test(req.params.token))return{valid:false,reason:'unknown'};const rows=await sql`SELECT state,active_confirmed,expires_at,public_name,unit_number,public_photo,vehicle_details,kind FROM roster_verification_cards WHERE token_hash=${hashToken(req.params.token)}`;const r=rows[0];if(!r)return{valid:false,reason:'unknown'};const disclosure=validityDisclosure(cardValidity(r.state,r.active_confirmed,new Date(r.expires_at),new Date()),{name:r.public_name,unitNumber:r.unit_number,photo:r.public_photo},r.kind);return disclosure.valid&&r.kind==='vehicle'&&vehicleDisclosureApproved?{...disclosure,vehicle:r.vehicle_details}:disclosure;});
}
