import { randomBytes } from 'node:crypto';

/**
 * Offer codes.
 *
 * These replace the legacy 4-digit `call_id`, which was both collision-prone
 * (~50% chance of a repeat after ~112 trips) and used as the authorisation
 * value for SMS acceptance — so a volunteer texting "4821-YES" could be
 * assigned to the wrong ride.
 *
 * A code is:
 *   - 10 characters of Crockford base32 → 50 bits of entropy, ~1.1e15 values;
 *   - generated by the CSPRNG, never derived from trip data;
 *   - stored only as a SHA-256 hash;
 *   - bound to one volunteer and one offer;
 *   - single-use and expiring;
 *   - useless once the offer is resolved.
 *
 * Crockford base32 omits I, L, O and U, so there is no ambiguity when someone
 * types it off a phone screen, and decoding is case-insensitive.
 */
const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
const CODE_LENGTH = 10;

export function generateOfferCode(): string {
  const bytes = randomBytes(CODE_LENGTH);
  let out = '';
  for (let i = 0; i < CODE_LENGTH; i += 1) {
    out += ALPHABET[bytes[i]! % ALPHABET.length];
  }
  return out;
}

/** Accepts what a human actually types: lower case, spaces, hyphens, O/0, I/1. */
export function normalizeOfferCode(input: string): string | null {
  const cleaned = input
    .trim()
    .toUpperCase()
    .replace(/[\s-]/g, '')
    .replace(/O/g, '0')
    .replace(/[IL]/g, '1')
    .replace(/U/g, 'V');
  if (cleaned.length !== CODE_LENGTH) return null;
  for (const ch of cleaned) if (!ALPHABET.includes(ch)) return null;
  return cleaned;
}

/** Display form, grouped for legibility: ABCDE-FGHJK */
export function formatOfferCode(code: string): string {
  return `${code.slice(0, 5)}-${code.slice(5)}`;
}
